create database Flight_Analysis;
use flight_analysis;
SELECT * FROM flight_analysis.meta_data;


create table Airline (
	Airline_ID int primary key,
    UNIQUE_CARRIER varchar(10),
    UNIQUE_CARRIER_NAME varchar(100),
    UNIQUE_CARRIER_ENTITY varchar (10)
);

create table Airport(
	AIRPORT_ID Int Primary key,
    AIRPORT_SEQ_ID int,
    CITY_MARKET_ID int,
    AIRPORT_CODE VARCHAR (10),
    CITY_NAME VARCHAR (100),
    STATE_ABR CHAR(2),
    STATE_FIPS INT,
    STATE_NM varchar(100),
    WAC INT
);

CREATE TABLE Flight (
    FLIGHT_ID INT AUTO_INCREMENT PRIMARY KEY,
    AIRLINE_ID INT,
    ORIGIN_AIRPORT_ID INT,
    DEST_AIRPORT_ID INT,
    DISTANCE FLOAT,
    DISTANCE_GROUP INT,
    YEAR INT,
    QUARTER INT,
    MONTH INT,
    CLASS CHAR(1),
    FOREIGN KEY (AIRLINE_ID) REFERENCES Airline(AIRLINE_ID),
    FOREIGN KEY (ORIGIN_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID),
    FOREIGN KEY (DEST_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID)
);

CREATE TABLE FlightMetrics (
    FLIGHT_ID INT,
    PASSENGERS FLOAT,
    FREIGHT FLOAT,
    MAIL FLOAT,
    FOREIGN KEY (FLIGHT_ID) REFERENCES Flight(FLIGHT_ID)
);

CREATE TABLE City (
	City_id INT AUTO_INCREMENT PRIMARY KEY,
    CityName VARCHAR(100),
    STATE_ABR CHAR(2),
    State_NM varchar(100) 
    );
    